Many fixes

diff --git a/.github/workflows/create-release.yml b/.github/workflows/create-release.yml
--- a/.github/workflows/create-release.yml
+++ b/.github/workflows/create-release.yml
@@ -19,15 +19,24 @@ jobs:
       - uses: actions/checkout@v2
       - name: Release checks and update version for release
         run: |
-          cd java
-          /scripts/release-checks.sh --java --maven pom.xml
+          git checkout -b release
+          /scripts/release-checks.sh --java --maven java/pom.xml
+          /scripts/release-checks.sh --python python/setup.cfg
+          /scripts/release-checks.sh --python python/setup.py
+          # /scripts/release-checks.sh --csharp cs/evolve-grpc.csproj
           FILE=docs/release.md
           if [ -f "$FILE" ]; then
             export release_date=$(date +'%d %B %Y')
-            /scripts/finalize-version.sh --java --maven pom.xml $FILE 'sed -i -e "s/TBD/$release_date/g"'
+            /scripts/finalize-version.sh --java --maven --no-commit pom.xml $FILE 'sed -i -e "s/TBD/$release_date/g"'
           else
-            /scripts/finalize-version.sh --java --maven pom.xml
+            /scripts/finalize-version.sh --java --maven --no-commit pom.xml
           fi
+          /scripts/finalize-version.sh --python --no-commit python/setup.cfg
+          /scripts/finalize-version.sh --python --no-commit python/setup.py
+          /scripts/finalize-version.sh --csharp --no-commit cs/evolve-grpc.csproj
+          commit_finalize_version
+          version=$(xmlstarlet pyx java/pom.xml | grep -v ^A | xmlstarlet p2x | xmlstarlet sel -t -v "/project/version")
+          echo "::set-output name=release-version::$(echo v$version)"
         shell: bash
 
   java-deploy:
@@ -55,6 +64,7 @@ jobs:
           GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
           GPG_KEY_PASSWORD: ${{ secrets.GPG_KEY_PASSWORD }}
           POM_PATH: java/pom.xml
+        continue-on-error:
 
   python-deploy:
     needs: release-checks
@@ -86,7 +96,13 @@ jobs:
           python build.py --fullclean
           python build.py --package
           twine upload --repository-url "$ZEPBEN_PYPI_REPO" -u "$ZEPBEN_PYPI_USERNAME" -p "$ZEPBEN_PYPI_PASSWORD" dist/*
+          artifact="zepben.protobuf-${version}-py3-none-any.whl"
+          echo "::set-output name=artifact::$(echo $artifact)"
+          echo "::set-output name=artifact-path::$(echo python/dist/$artifact)"
         shell: bash
+        with:
+          version: ${{ needs.release-checks.outputs.release-version }}
+        continue-on-error:
 
   cs-deploy:
     needs: release-checks
@@ -100,6 +116,8 @@ jobs:
       ZEPBEN_NUGET_UPLOAD_FEED: ${{ secrets.ZEPBEN_NUGET_UPLOAD_FEED }}
     steps:
       - uses: actions/checkout@v2
+        with:
+          ref: release
 
       - name: Cache C# deps
         uses: actions/cache@v2
@@ -117,7 +135,13 @@ jobs:
           dotnet restore evolve-grpc.csproj --configfile Nuget.Config
           dotnet pack evolve-grpc.csproj -c Release -o ./ --no-restore
           dotnet nuget push *.nupkg -k $ZEPBEN_NUGET_UPLOAD_KEY -s $ZEPBEN_NUGET_UPLOAD_FEED
+          artifact="Zepben.Evolve.Grpc.${version}.nupkg"
+          echo "::set-output name=artifact::$(echo $artifact)"
+          echo "::set-output name=artifact-path::$(echo cs/$artifact)"
         shell: bash
+        with:
+          version: ${{ needs.release-checks.outputs.release-version }}
+        continue-on-error:
 
   finalise:
     needs: [java-deploy, python-deploy, cs-deploy]
@@ -125,8 +149,16 @@ jobs:
     container: zepben/pipeline-basic:5.1.0
     steps:
       - uses: actions/checkout@v2
+
+      - name: Delete release branch if deploy failed and fail
+        if: needs.java-deploy.result == 'failure' || needs.cs-deploy.result == 'failure' || needs.python-deploy.result == 'failure'
+        run: |
+          git push origin -d release
+          echo "There was an error in the mvn deploy command above."
+          exit 1
+        shell: bash
+
       - name: Merge and Tag
-        if: needs.java-deploy.result == 'success' && needs.cs-deploy.result == 'success' && needs.python-deploy.result == 'success'
         id: merge
         run: |
           git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
@@ -141,7 +173,6 @@ jobs:
         shell: bash
 
       - name: Create Release
-        if: needs.java-deploy.result == 'success' && needs.cs-deploy.result == 'success' && needs.python-deploy.result == 'success'
         id: create_release
         uses: actions/create-release@v1
         env:
@@ -154,23 +185,35 @@ jobs:
           prerelease: false
 
       - name: Upload Release Asset
-        if: needs.java-deploy.result == 'success' && needs.cs-deploy.result == 'success' && needs.python-deploy.result == 'success'
         uses: actions/upload-release-asset@v1
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           upload_url: ${{ steps.create_release.outputs.upload_url }}
-          asset_path: ${{ steps.merge.outputs.artifact-path }}
-          asset_name: ${{ steps.merge.outputs.artifact }}
+          asset_path: ${{ needs.java-deploy.outputs.artifact-path }}
+          asset_name: ${{ needs.java-deploy.outputs.artifact }}
           asset_content_type: application/zip
 
-      - name: Fail build
-        if: needs.java-deploy.result == 'failure' || needs.cs-deploy.result == 'failure' || needs.python-deploy.result == 'failure'
-        run: |
-          git push origin -d release
-          echo "There was an error in the mvn deploy command above."
-          exit 1
-        shell: bash
+      - name: Upload Release Asset
+        uses: actions/upload-release-asset@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          upload_url: ${{ steps.create_release.outputs.upload_url }}
+          asset_path: ${{ needs.cs-deploy.outputs.artifact-path }}
+          asset_name: ${{ needs.cs-deploy.outputs.artifact }}
+          asset_content_type: application/octet-stream
+
+      - name: Upload Release Asset
+        uses: actions/upload-release-asset@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          upload_url: ${{ steps.create_release.outputs.upload_url }}
+          asset_path: ${{ needs.python-deploy.outputs.artifact-path }}
+          asset_name: ${{ needs.python-deploy.outputs.artifact }}
+          asset_content_type: application/octet-stream
+
 
   update-version:
     needs: finalise
@@ -186,34 +229,27 @@ jobs:
       SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
     steps:
       - uses: actions/checkout@v2
-        if: needs.finalise.result == 'success'
         with:
           ref: release
+
       - name: Update to next minor version
-        if: needs.finalise.result == 'success'
         run: |
           source /scripts/common.sh
 
           cd python
-          /scripts/update-version.sh --python --no-commit --release setup.cfg
+          /scripts/update-version.sh --python --no-commit setup.cfg
+          /scripts/update-version.sh --python --no-commit setup.py
           cd ../java
-          /scripts/update-version.sh --java --maven --release --no-commit pom.xml
+          /scripts/update-version.sh --java --maven --no-commit pom.xml
           cd ../cs
-          /scripts/update-version.sh --csharp --release --no-commit evolve-grpc.csproj
+          /scripts/update-version.sh --csharp --no-commit evolve-grpc.csproj
           commit_update_version
-        shell: bash
 
-      - uses: actions/checkout@v2
-        if: needs.finalise.result == 'success'
-        with:
-          ref: main
-
-      - name: Merge release
-        if: needs.finalise.result == 'success'
-        run: |
           git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
           git fetch --all
-          git merge origin/release
-          git push origin ${GITHUB_REF/refs\/heads\//}
+          git checkout main
+          git pull
+          git merge release
+          git push origin main
           git push origin -d release
         shell: bash
